# Generated by Django 5.1.2 on 2024-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Лига', 'verbose_name_plural': 'Лиги'},
        ),
        migrations.AlterModelOptions(
            name='playertask',
            options={'verbose_name': 'Задание игрока', 'verbose_name_plural': 'Задания игроков'},
        ),
        migrations.AlterModelOptions(
            name='referralsystem',
            options={'verbose_name': 'Реферальная система', 'verbose_name_plural': 'Реферальная системы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задания', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='reward_tickets',
            field=models.IntegerField(default=0, verbose_name='Награда (билеты)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_all',
            field=models.IntegerField(default=1000, verbose_name='Количество баллов игрока за месяц'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tickets',
            field=models.IntegerField(default=2, verbose_name='Текущее количество билетов игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tickets_all',
            field=models.IntegerField(default=2, verbose_name='Количество билетов игрока за месяц'),
        ),
    ]
