# Generated by Django 5.1.2 on 2024-12-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_alter_league_options_alter_playertask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='premium_tickets',
            field=models.IntegerField(default=0, verbose_name='Текущее количество премиум билетов игрока'),
        ),
        migrations.AddField(
            model_name='player',
            name='premium_tickets_all',
            field=models.IntegerField(default=0, verbose_name='Количество премиум билетов игрока за месяц'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tickets',
            field=models.IntegerField(default=0, verbose_name='Текущее количество билетов игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tickets_all',
            field=models.IntegerField(default=0, verbose_name='Количество билетов игрока за месяц'),
        ),
    ]
