# Generated by Django 5.1.2 on 2024-12-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_player_premium_tickets_player_premium_tickets_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для выполнения задания'),
        ),
    ]
